# Configure logging levels for Hibernate and Spring Framework
#logging:
#  level:
#    org:
#      hibernate: trace
#      springframework: trace

# Management endpoints configuration
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    port: 9090
# URLs for accessing Actuators:
# - http://localhost:9090/actuator (Actuator endpoint)

# URLs for accessing Swagger UI:
# - http://localhost:9090/actuator/swagger-ui/index.html (Swagger endpoint)

# Configure Spring Boot Admin client settings
spring:
  boot:
    admin:
      client:
        instance:
          metadata:
            tags:
              environment: QA
        url: http://localhost:8080
# URLs for accessing Spring Boot Admin:
# - http://localhost:8080/applications (Actuator endpoint)

# Configure the database connection
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todo?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: ${DATABASE_PASSWORD_ENV_VAR}
#    password: ENC(I0BXUCm0vCiASShRUucwIA==)
    
# Configure JPA settings for database interaction
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

# Configure Springdoc (Swagger) settings
springdoc:
  api-docs:
    enabled: true
  show-actuator: true
  swagger-ui:
    enabled: true
  use-management-port: true

# Configure Jasypt encryption settings
jasypt:
  encryptor:
    password: ${MY_KEY_VAR}
    algorithm: PBEWithMD5AndDES
#    environment-variable-name: MY_ENCRYPTION_KEY_ENV_VAR


#http://localhost:9090/actuator/swagger-ui/

#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=user@mail.com
#spring.mail.password=user@987
#spring.boot.admin.notify.mail.to=user@mail.com

#spring.mail.properties.mail.smtp.starttls.enable=true

